# Generated by Django 4.1.10 on 2024-03-13 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_audio_segment_alter_audiogeneration_audio'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='audio_segment',
            options={'ordering': ['start_time']},
        ),
        migrations.AddField(
            model_name='audio_segment',
            name='content',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
