# Generated by Django 4.1.10 on 2024-03-13 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_audio_segment_options_audio_segment_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audio_segment',
            name='content',
        ),
    ]
